title: Patrick Bell # your name (or website title) here
logo: "/images/headshot_round.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Agricultural Scientist | Nonprofit Executive | Data Science Dabbler
  <br><br>
  <a href="https://www.linkedin.com/in/patrick-bell-bb1b7537/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
